# Generated by Django 3.2.9 on 2023-05-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
