# Generated by Django 3.2.9 on 2023-05-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_category_blogcity_ulke_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcity',
            name='ulke_id',
        ),
    ]
