# Generated by Django 3.2.9 on 2023-05-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blogcity_ulke_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcity',
            name='category_ulke',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
