# Generated by Django 3.2.9 on 2023-05-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_tripcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcity',
            name='category_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcity'),
        ),
    ]
