# Generated by Django 3.2.9 on 2023-05-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcity',
            old_name='category',
            new_name='ulke_id',
        ),
    ]
